import { SidebarLayout } from "@/modules/SidebarLayout/SidebarLayout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={"dark"}>
            <body className={inter.className}>
                <SidebarLayout>
                    <div className="w-full bg-[#4B4B4B] rounded-l-3xl">
                        {children}
                    </div>
                </SidebarLayout>
            </body>
        </html>
    );
}
